name: Deploy AWS SAM Application

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install SAM CLI
        run: |
          sudo apt update
          sudo apt install unzip -y
          curl -Lo /tmp/sam-installation.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          sudo unzip -d /usr/local/bin /tmp/sam-installation.zip

      - name: Validate SAM template
        run: sam validate -t template.yaml

      - name: Deploy SAM application
        run: sam deploy --stack-name hospital-managment-system --s3-bucket capstone-cicd-yosief.abraham --parameter-overrides CognitoDomain=project-cicd-capstone-yosief-abraham S3Bucket=capstone-cicd-yosief.abraham FrontendDeployment=local --capabilities CAPABILITY_IAM

      # Add more steps as needed for testing, monitoring, etc.







